### ISSUE TITLE
Implicit declaration of function 'SDThemeManagerApplyStyle' is invalid in C99

### ISSUE THREAD

**Issue by MichleMin** [SysdataSpA/R.objc#10]

**Comment by grzegorzkrukowski** [comment]
I found workaround for this:

Use `-skip-themes`:

`"${PODS_ROOT}/R.objc/Robjc"  --skip-themes -p "$SRCROOT"`

**Comment by guidosabatini-sysdata** [comment]
Sorry for not responding.
I have no details to help you with your problem, but @grzegorzkrukowski is right: if you don't need to use [Giotto](https://github.com/SysdataSpA/Giotto) you can skip the themes part of R with the `-skip-themes` option
