### ISSUE TITLE
Duplicatating RLaunchScreen

### ISSUE THREAD

**Issue by yurikoles** [SysdataSpA/R.objc#13]
```objc
@interface RLaunchScreen: NSObject
- (__kindof UIViewController*)instantiateInitialViewController;
@end


@interface RLaunchScreen: NSObject
- (__kindof UIViewController*)instantiateInitialViewController;
@end


@interface RStoryboards: NSObject
- (RProfile*)profile;
- (RLaunchScreen*)launchScreen;
- (RMain*)main;
- (RLaunchScreen*)launchScreen;
- (RLaunchScreen*)launchScreen;
@end
```

Similar duplication is in R.m.

**Comment by guidosabatini-sysdata** [comment]
Do you have two storyboards with the same name (LaunchScreen.storyboard) in you project?

**Comment by yurikoles** [comment]
No, I have only one, but with localization.

![2018-07-23 18 51 18](https://user-images.githubusercontent.com/922873/43087815-69b52bd4-8ea9-11e8-9f44-12362ca5c690.png)

**Comment by guidosabatini-sysdata** [comment]
I tried your case but no problems appeared. Could you please check in the filesystem if there are more than one storyboards with the same LaunchScreen name?
R.objc doesn't check on project files but directly on filesystem: they could be here but not in the project

**Comment by yurikoles** [comment]
@guidosabatini-sysdata I had sent a PR #14 to address this issue for beginners.

**Comment by yurikoles** [comment]
In my case it was Pods :(
