### ISSUE TITLE
[FR]Load resource via class methods?

### ISSUE THREAD

**Issue by yurikoles** [SysdataSpA/R.objc#17]
Please allow to load resources using class methods, e.g. images and storyboards.

In current implementation we need to spawn temporary obect to access resource.

**Comment by guidosabatini-sysdata** [comment]
What do you mean? Can you give me an example of the problem?

**Comment by yurikoles** [comment]
```objc
[[RImages new] userIconPlaceholder]
```
vs
```objc
[RImages userIconPlaceholder]
```

**Comment by guidosabatini-sysdata** [comment]
I think you misunderstook how R.objc works.
If you need the image named **userIconPlaceholder**, the correct way to get it is
`R.image.userIconPlaceholder`
or if you prefer
`[[R image] userIconPlaceholder]`

**Comment by yurikoles** [comment]
Thank you, I had missed it in `R.h`.
