### ISSUE TITLE
Command /bin/sh failed with exit code 255

### ISSUE THREAD

**Issue by bianca-stana** [SysdataSpA/R.objc#18]
Hi!

I have followed Getting started, but on build I got this error at the strings step: `NSURLErrorDomain (-1016)` => `kCFURLErrorCannotDecodeContentData ` (my localization strings are organized in a bundle, which is located directly in the project folder).

**Comment by guidosabatini-sysdata** [comment]
I'm afraid R.objc isn'y compatible with bundles right now
