### ISSUE TITLE
storyboard identifier not support tableViewController ?

### ISSUE THREAD

**Issue by Hext123** [SysdataSpA/R.objc#4]
I found a problem in the course of my use:  

<https://github.com/SysdataSpA/R.objc/blob/master/R.objc/Sources/StoryboardsGenerator.m#L115>  

The code here is only handled: `viewController` `navigationController` `pageViewController` `viewControllerPlaceholder`  

storyboard identifier not support: `tableViewController` `collectionViewController` `tabBarController` 
and `splitViewController` `glkViewController` `avPlayerViewController`
  
.  
  
Sorry, my English is not good.
Hope you can understand what I'm talking about

**Comment by guidosabatini-sysdata** [comment]
You are right, actually R.objc only supports viewControllers, navigationControllers and pageViewControlles.
We will update soon, but if you want to fork the project, modify it and send a pull request you are welcome ;)

**Comment by xz410236056** [comment]
why not use __kindof?
