### ISSUE TITLE
如何调用

### ISSUE THREAD

**Issue by ZClee128** [SysdataSpA/R.objc#7]
R.string.localizable这个怎么调用的

**Comment by guidosabatini-sysdata** [comment]
To use R.string, you just need to use localizable.strings files in your app and follow the instructions to setup R.objc.
It will automatically scan your project for *.strings files anche expose them and all the strings in them by name in the format **R.string._<strings_filename>_._<string_key>_**

**PAY ATTENTION**: a conversion of the filename and the key will be applied (non alphanumeric characters trimming and camelcasing)

**Example:**
if you have an app with a Localizable.strings file like this:
```
"common_proceed" = "Proceed";
"common_cancel" = "Cancel";
"common_ok" = "OK";
```
you can get a string by `R.string.localizable.commonProceed`
