### ISSUE TITLE
code conflict when merge?

### ISSUE THREAD

**Issue by foobra** [SysdataSpA/R.objc#8]
If two people add image independently, the R will conflict
Can R.objc keep sort stability?

**Comment by guidosabatini-sysdata** [comment]
It's a good idea for a new feature, thank you. 
Please notice therefore that R file is completely regenerated each time you compile your project (perhaps if it needs to). So you can merge in every way (keep mine, keep theirs, mark as merged) and simply recompile your project to solve the problem. 

--
Guido Sabatini
Head of iOS development

Sysdata S.p.A. - Via dè Carracci, 13 - 40129 Bologna
E: guido.sabatini@sysdata.it
T: +39 0514144925
W: http://www.sysdata.it
